### ISSUE TITLE
in(x, s::AVLSet) uses Base implementation that iterates through the set instead of using the tree data structure to lookup quickly

### ISSUE THREAD

**Issue by krynju** [krynju/AVLTrees.jl#9]
```
julia> @which 10 in AVLSet([10])
in(x, itr) in Base at operators.jl:1129
```

implementing Base.in(x, s::AVLSet) breaks tests as all(items .∈ Ref(set)) operations break for whatever reason

**Comment by p-casgrain** [comment]
I am curious about why it does this. I had thought the canonical way of extending `in` would have been to extend `Base.in` specifically. Is there a guide on best practices for this kind of thing?

**Comment by krynju** [comment]
I've done some investigation and other data structures seem to only implement Base.in(). 

With Base.in implemented the @which for non-ref returns the correct function (the one implemented within the package). The @which for the Ref(set) still returns the Base implementation that uses iteration (but with Base.in implemented it doesn't work correctly. 

I've tested this on 1.7 beta 3. Need to check on a different version

**Comment by krynju** [comment]
Turns out findkey just returns the `node.data` if it finds the key, which is `nothing` in case of a Set, might change that to a (key=>data) pair later to be honest. Used the find_node version instead

Implementation will be added in https://github.com/krynju/AVLTrees.jl/pull/10
